server:
  port: 8888
spring:
  r2dbc:
    name: r2dbc
    url: r2dbcs:mysql://localhost:3306/boss?serverTimezone=GMT&SSL=false&sslMode=DISABLED
    username: root
    password: 123456
    pool:
      enabled: true
      validation-query: SELECT 1
  jackson:
    locale: zh_CN
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:MM:ss
    serialization:
      # \u7981\u6B62\u5C06 java.util.Date, Calendar \u5E8F\u5217\u5316\u4E3A\u6570\u5B57(\u65F6\u95F4\u6233)
      WRITE_DATES_AS_TIMESTAMPS: false
      # \u5E8F\u5217\u5316\u65F6\uFF0C\u5BF9\u8C61\u4E3A null\uFF0C\u662F\u5426\u629B\u5F02\u5E38
      FAIL_ON_EMPTY_BEANS: false
    deserialization:
      # \u53CD\u5E8F\u5217\u5316\u65F6\uFF0Cjson \u4E2D\u5305\u542B pojo \u4E0D\u5B58\u5728\u5C5E\u6027\u65F6\uFF0C\u662F\u5426\u629B\u5F02\u5E38
      fail-on-unknown-properties: false
    property-naming-strategy: LOWER_CAMEL_CASE
    visibility:
      getter: any






logging:
  level:
    org.springframework.r2dbc: debug

