server:
  port: 8070

spring:
  application:
    name: admin-server


security:
  user:
    name: admin
    password: 123456
  basic:
    enabled: false

eureka:
  #自己编写，用于修改注册中心的服务地址
  serverUrl: 127.0.0.1
  port: 8010
  client:
    service-url:
      defaultZone: http://${security.user.name}:${security.user.password}@${eureka.serverUrl}:${eureka.port}/eureka/
    registry-fetch-interval-seconds: 5
  instance:
    instance-id:  ${spring.cloud.client.ipAddress}:${server.port}(${spring.application.name})
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    health-check-url-path: /actuator/health
    metadata-map:
      user.name: ${security.user.name}
      user.password: ${security.user.password}



