server:
  port: 18000
  servlet:
    context-path: api
#\u6CE8\u518C\u4E2D\u5FC3\u5730\u5740
register:
  ip: 127.0.0.1
spring:
  profiles:
    active: dev
  application:
    name: service-gateway
  cloud:
    nacos:
      #nacos config
      config:
        file-extension: yml
        server-addr: ${register.ip}:8848
      discovery:
        service: ${spring.application.name}
        server-addr: ${register.ip}:8848
        group:  ${NACOS_GROUP:DEFAULT_GROUP}
    ############################
# gateway-Route
#    id\uFF0C\u8DEF\u7531\u6807\u8BC6\u7B26\uFF0C\u533A\u522B\u4E8E\u5176\u4ED6 Route\u3002
#    uri\uFF0C\u8DEF\u7531\u6307\u5411\u7684\u76EE\u7684\u5730 uri\uFF0C\u5373\u5BA2\u6237\u7AEF\u8BF7\u6C42\u6700\u7EC8\u88AB\u8F6C\u53D1\u5230\u7684\u5FAE\u670D\u52A1\u3002
#    order\uFF0C\u7528\u4E8E\u591A\u4E2A Route \u4E4B\u95F4\u7684\u6392\u5E8F\uFF0C\u6570\u503C\u8D8A\u5C0F\u6392\u5E8F\u8D8A\u9760\u524D\uFF0C\u5339\u914D\u4F18\u5148\u7EA7\u8D8A\u9AD8\u3002
#    predicate\uFF0C\u65AD\u8A00\u7684\u4F5C\u7528\u662F\u8FDB\u884C\u6761\u4EF6\u5224\u65AD\uFF0C\u53EA\u6709\u65AD\u8A00\u90FD\u8FD4\u56DE\u771F\uFF0C\u624D\u4F1A\u771F\u6B63\u7684\u6267\u884C\u8DEF\u7531\u3002
#    filter\uFF0C\u8FC7\u6EE4\u5668\u7528\u4E8E\u4FEE\u6539\u8BF7\u6C42\u548C\u54CD\u5E94\u4FE1\u606F\u3002
##########################
    gateway:
      discovery:
        locator:
          #\u8868\u660Egateway\u5F00\u542F\u670D\u52A1\u6CE8\u518C\u548C\u53D1\u73B0\u7684\u529F\u80FD\uFF0C
          #\u5E76\u4E14spring cloud gateway\u81EA\u52A8\u6839\u636E\u670D\u52A1\u53D1\u73B0\u4E3A\u6BCF\u4E00\u4E2A\u670D\u52A1\u521B\u5EFA\u4E86\u4E00\u4E2Arouter\uFF0C
          #\u8FD9\u4E2Arouter\u5C06\u4EE5\u670D\u52A1\u540D\u5F00\u5934\u7684\u8BF7\u6C42\u8DEF\u5F84\u8F6C\u53D1\u5230\u5BF9\u5E94\u7684\u670D\u52A1
          enabled: true
          lower-case-service-id: true
          filters: # \u8FC7\u6EE4\u5668
            - StripPrefix=1
      # \u8DEF\u7531\uFF08routes\uFF1A\u8DEF\u7531\uFF0C\u5B83\u7531\u552F\u4E00\u6807\u8BC6\uFF08ID\uFF09\u3001\u76EE\u6807\u670D\u52A1\u5730\u5740\uFF08uri\uFF09\u3001
      #\u4E00\u7EC4\u65AD\u8A00\uFF08predicates\uFF09\u548C\u4E00\u7EC4\u8FC7\u6EE4\u5668\u7EC4\u6210\uFF08filters\uFF09\u3002filters \u4E0D\u662F\u5FC5\u9700\u53C2\u6570\u3002
      routes:
        - id: consumer-route
#          url: http://10.89.104.26:18002/
          uri: lb://service-consumer
          # \u8DEF\u7531\u6761\u4EF6\uFF08predicates\uFF1A\u65AD\u8A00\uFF0C\u5339\u914D HTTP \u8BF7\u6C42\u5185\u5BB9\uFF09
          predicates:
            - Path=/consumer/**
          filters: # \u8FC7\u6EE4\u5668
            - StripPrefix=1
#            - name:  Hystrix
#              args:
#                name: fallbackCmd
#                fallbackUri: forward:/fallback #fallback\u5BF9\u5E94\u7684uri

    sentinel:
      transport:
        dashboard: localhost:8080  #sentinel\u63A7\u5236\u53F0\u7684\u8BF7\u6C42\u5730\u5740
        port: 8080
      eager: true # \u670D\u52A1\u542F\u52A8\u76F4\u63A5\u5EFA\u7ACB\u5FC3\u8DF3\u8FDE\u63A5
#      datasource:
#        ds1 :
#          nacos:
#            server-addr: localhost:8848
#            data-id: sentinel  # \u8BFB\u53D6\u914D\u7F6E\u6587\u4EF6\u7684 data-id
#            group-id: DEFAULT_GROUP
#            data-type: json  #  \u8BFB\u53D6\u57F9\u8BAD\u6587\u4EF6\u7C7B\u578B\u4E3Ajson
#            rule-type: flow  #\u8DEF\u7531\u5B58\u50A8\u89C4\u5219

management:
  endpoints:
    web:
      exposure:
        include: '*'
